apiVersion: apps/v1
kind: Deployment
metadata:
  name: compiled-whisper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compiled-whisper
  template:
    metadata:
      labels:
        app: compiled-whisper
    spec:
      containers:
      - name: compiled-whisper
        image: your-registry/compiled-whisper:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: model-storage
          mountPath: /app/s2a-q4-hq-fast-en%2Bpl.model
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: compiled-whisper
spec:
  selector:
    app: compiled-whisper
  ports:
  - port: 80
    targetPort: 5001
  type: LoadBalancer 