apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pv.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: compiled-whisper
  app.kubernetes.io/part-of: compiled-whisper 